name: Java CI

on:
  push:
    branches: [ci_integration]
  pull_request:
    branches: [ci_integration]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: '19'
      - name: Build with Maven
        run: mvn -B package --file LocationFinder/pom.xml -Dmaven.test.skip=true
      - name: Run ClientTest
        run: cd LocationFinder && mvn -Dtest=ClientTest test
      - name: Run LocationTest
        run: cd LocationFinder && mvn -Dtest=LocationTest test
      - name: Export test results
        run: cp LocationFinder/target/surefire-reports/*.txt UnitTests
      - uses: EndBug/add-and-commit@v7
        with:
          add: UnitTesting/.
          default_actor: github_actions